package org.clyze.persistent.model;

import java.util.Set;
import java.util.HashSet;

/**
 * A class providing a common container of basic Doop metadata.
 *
 * The metadata is generated by processing some form of a
 * syntactic representation (e.g. Java source file, Jimple IR).
 */
public class BasicMetadata {
    public final Set<Class> classes                  = new HashSet<>();
    public final Set<Field> fields                   = new HashSet<>();
    public final Set<Method> methods                 = new HashSet<>();
    public final Set<Variable> variables             = new HashSet<>();
    public final Set<MethodInvocation> invocations   = new HashSet<>();
    public final Set<HeapAllocation> heapAllocations = new HashSet<>();
    public final Set<Usage> usages                   = new HashSet<>();
    public final Set<StringConstant> stringConstants = new HashSet<>();
}
